### ISSUE TITLE
Non-human-readable Variants

### ISSUE THREAD

**Issue by chrischen** [rescript-association/genType#457]
When I use a Belt.Result Ok/Error type in JS, the Variant is converted with human-friendly tag names. However when I use the Relude_Validation's VOk or VError types it gets converted to integer tag names in JS:

```{ tag: 'Error', value: { _0: 0, _1: 0 } }```

It gets generated the same way in the bs.js file.

I'm not sure if the problem is some incompatibility with Relude, since my own variant tags get generated as `{tag: 'HumanReadable' }` whereas everything inside a Relude tag gets converted to `{TAG: 0 }` style, or if this is actually a problem with genType as the Relude maintainer suggested.

More info here: https://github.com/reazen/relude/issues/279
https://reasonml.chat/t/relude-variants-and-interop-with-js/2480

**Comment by mlms13** [comment]
Ah, from the Discourse I thought you were talking about `Relude_Result`, which is just an alias for the stdlib result. I missed the part about `Validation`.

I'm not very familiar with how genType works. Is the idea that `[@genType]` needs to be added to every type definition? That seems like a significant cost for a library to take on (since we'd presumably be passing the gentype dependency on to our users), and in general we've been trying to avoid adding new ReScript-specific code to Relude.

My preference would be for users of Relude to be able to get genType functionality without Relude having to add genType directly, but I'm not sure if that's currently possible.

**Comment by chrischen** [comment]
From what I've been doing so far I've only been adding [@genType] annotation to any function I want to use from the JS/TS side. It then converts all dependencies from what I can tell. It's been working with my own code (and my own implementation of Validation). So if Relude is just regular Reason code I'm not sure why its variants are generated in a completely different format. For what it's worth, it doesn't seem like it's a genType specific thing since the regular bucklescript generated JS also have the tags in a different format that is not human-readable.

**Comment by cristianoc** [comment]
There's some limited (rarely used) support for third party dependencies people have tried. However, the dependencies (relude, or something else) should already annotate anything that will be exported.
